language: node_js
node_js:
   - "0.10"
after_script:
   - npm run zuul
   - npm run coveralls
env:
  - global:
    - secure: W0qoI1cvVeuok9BwJG0HMs9Q3iJ6RpDlYoVccDoXyt1XyPyeogslDZId9+tonMchlfXYkHgZhup3WmvfCkYqrfntVXDcc2x4l/dFheHNxuQNgqR3NXClQkeoZbWpH9bW66cZYjViGbIPTG8gwVPmQ9UyNs/mE46Z47pjrNflnoU=
    - secure: Qrhmhma9oGiWipmSM3hmupshDo/8K917iAaCtv8dywJMJw36I1q1MzguQqAvViURHIZeLilnNpkgd3ZkTsBvHlK9mXcsBKh6SOG4wQKxnLHsfueep67FqocFRCr6+MUcThnTvKfeDEkAiuEYMj3m0U9l3J1K6Ougij3giLXi0Bo=
