language: node_js
node_js:
   - "0.10"
after_script:
   - npm run zuul
   - npm run coveralls
env:
  global:
    - secure: aygd1S9VazTZoQawjZbsBJkOACaUifCtH58d8FS+KjMFzJEcgCpAl1Q2ut91sGICwLnFF96Kne9ItwVuCrEYMmHUIc7I/zVs2NfJgRRz1cEuizpoIfdYFh4nlSgDqtomdO4hRWGm+2ZySqWEsZN6wGSnoCosweJTz+HsCI5kQgc=
    - secure: XZ/dd9VGbJdr6wSo7lSP/34K+uNpKV+rVPBYImpqXpgytJHYnIipc9Pu3chcjnZbXqQoL/sP2dOL57ETHQ8V2zpRilmFKL2ruzyuxNdrLvzMhmblOU0Mq0+nxfkbMFfrQ1u39x6RW0TuEjEGb/eB/nZL0wtWD/CWv4UmQIogvJk=
